# Livello minimo di log mostrato in console
# Valori possibili: trace, debug, info, warn, error
org.slf4j.simpleLogger.defaultLogLevel=debug

# Mostra la data e ora nel log
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss

# Mostra il nome del thread
org.slf4j.simpleLogger.showThreadName=true
